### ISSUE TITLE
Installation with CMake 

### ISSUE THREAD

**Issue by JeRo84** [asmaloney/MeshIO#4]
I have several errors when i try to install the Plugin via CMake.
The latest error is:
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Error at CMakeLists.txt:9 (AddPlugin):
Unknown CMake command "AddPlugin".

**How To Reproduce**
- Start CMake as Admin on Win10
- Browse "Where is the Source Code" to C:/Program Files/CloudCompare/plugins/private/MeshIO
- Browse "Where to build the binaries" to C:/Program Files/CloudCompare/plugins
- Click on Configure and check "PLUGIN-3rdParty_MESH_IO
- Click on Configure again and see the following Error:
    Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
    The C compiler identification is MSVC 19.28.29913.0
    The CXX compiler identification is MSVC 19.28.29913.0
    Detecting C compiler ABI info
    Detecting C compiler ABI info - done
    Check for working C compiler: C:/Program Files (x86)/Microsoft Visual 
    Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
    Detecting C compile features
    Detecting C compile features - done
    Detecting CXX compiler ABI info
    Detecting CXX compiler ABI info - done
    Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual 
    Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
    Detecting CXX compile features
    Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:9 (AddPlugin):
    Unknown CMake command "AddPlugin".

    CMake Warning (dev) in CMakeLists.txt:
    No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.20)

    should be added at the top of the file.  The version specified may be lower
    if you wish to support older CMake versions for this project.  For more
    information run "cmake --help-policy CMP0000".
    This warning is for project developers.  Use -Wno-dev to suppress it.

    Configuring incomplete, errors occurred!
    See also "C:/Program Files/CloudCompare/plugins/CMakeFiles/CMakeOutput.log".

**Screenshots**
![Screenshot 2021-04-09 211429](https://user-images.githubusercontent.com/82234937/114229787-97fd0980-9978-11eb-8c6a-799e19b585a1.png)

**Your Environment**
 - CloudCompare version (git hash/tag): v2.11.3
 - OS & Version: Win10 Pro
 - Qt Version: I dont know what QT means

**Comment by asmaloney** [comment]
_AddPlugin_ only exists on CloudCompare's "master" branch, so the first thing to check is that you're using the right version of **MeshIO** with the right version of CloudCompare.

I would recommend building with the "master" branch of CloudCompare, in which case you'll use the "master" branch of MeshIO as well.

If you need to build CloudCompare using the "v2.11.x" branch (which it looks like you're using), you will need to use the MeshIO tag "cloudcompare-2.11.x" (see note in README).

If that's not the issue, then I'll need to see if there are any changes to CloudCompare that require updating MeshIO...

**Comment by JeRo84** [comment]
I dont know what you mean with:  "master" branch of CloudCompare

I have noticed the note in README but I dont know what to do there... 

Sorry, I'm not a programmer. I'm a Surveyor who would only like to use this Plugin for importing IFC-Files.
It's late here in Germany and I will test again tomorrow.

Thank you so much for your help!

**Comment by JeRo84** [comment]
It may also be important that I use CloudCompare via "CloudCompare 2.11.3 installer version" and not via The Github Code.
Could this be my problem?

**Comment by asmaloney** [comment]
Yes :-)

You will need the CloudCompare source first. Then you clone this repository into the `CloudCompare/plugins/private` directory, turn it on in CloudComapre's CMake options, and build the whole thing.

I can see that the build instructions are not clear for anyone not familiar with git/cmake/building software. I will update them.

**Comment by JeRo84** [comment]
Now I can sleep better and dont break my head about this. 

So I will wait for the updated instructions.
Thank you very much!

**Comment by asmaloney** [comment]
Wait for it - you'll probably break your head trying to build CloudCompare! 🤯  You can post issues over there if you have problems though. (I don't use Windows for this, so I'm afraid I'm not much help.)

I have updated the README here.

**Comment by Icewulf666** [comment]
> Wait for it - you'll probably break your head trying to build CloudCompare! 🤯  You can post issues over there if you have problems though. (I don't use Windows for this, so I'm afraid I'm not much help.)
> 
> 
> 
> I have updated the README here.

Hej, i will try to compile it with JeRo84 next week. If we struggle we will come back for support. Thanks for help and have a great weekend.

Regards Marcus
