### ISSUE TITLE
Cloud I import other format by using this plugin？

### ISSUE THREAD

**Issue by FrozenCo** [asmaloney/MeshIO#5]
**Question**
Thank you for providing such a good plugin, but now I want to introduce other format files into Cloudcompare through this plugin and assimp.  Is this possible?

**Comment by asmaloney** [comment]
It's been a while since I looked at it, but I think it should be really easy?

I've never worked with 3ds, so I'm not familiar with the format, but I believe you just need to copy what glTF is doing.

**Comment by FrozenCo** [comment]
> It's been a while since I looked at it, but I think it should be really easy?
> 
> I've never worked with 3ds, so I'm not familiar with the format, but I believe you just need to copy what glTF is doing.

Thanks a lot, I've finished it.

**Comment by FrozenCo** [comment]
> It's been a while since I looked at it, but I think it should be really easy?
> 
> I've never worked with 3ds, so I'm not familiar with the format, but I believe you just need to copy what glTF is doing.

I'm sorry to bother you again. I use the plug-in to run in cloudcompare2.11.3. When loading COLLADA and glTF model files, the model will only be displayed at the beginning. When I click, rotate, and other operations, it will disappear and become transparent. How should I handle this? Thank you.

When I open the. dae file
![1](https://user-images.githubusercontent.com/103629575/210126500-902f7fd0-9970-448b-ad9b-43bb025e11da.png)

When I rotate an angle. The model disappear.
![2](https://user-images.githubusercontent.com/103629575/210126526-b434bb6e-ad53-4841-8b3a-be0e0798cb86.png)

**Comment by asmaloney** [comment]
(Moved to its own issue.)
