### ISSUE TITLE
Problems with version modified to use vcpkg

### ISSUE THREAD

**Issue by Niexiaoer** [asmaloney/MeshIO#7]
**Question**
Hello, thank you for your work.
I add the plugin as described by the readme. However, when I load the cloudcompare.exe, the plugin label is disabled(grey), and I can not load the dae and gltf file.

**Screenshots**
![image](https://user-images.githubusercontent.com/23131934/210318500-d09eca89-6c64-41de-82fb-07c2eef014cb.png)

**Additional context**

**Your Environment**
 - CloudCompare version (2.11.3):
 - OS & Version: windows vs 2015
 - Qt Version: 5.7.0

**Comment by asmaloney** [comment]
1. Are there any messages  in the console at the bottom? It should say whether the plugin was found and loaded, and if the extensions were properly registered.
2. Does the plugin show up in the "About Plugins" window? (Not sure where that menu item is on Windows.)
3. If it does not, make sure that the plugin DLL is in one of the paths listed at the bottom of that window.

**Comment by Niexiaoer** [comment]
Thank you for your reply. I checked the console and found that the software failed to load the MeshIO.dll and says that 
"MeshIO.dll does not seem to be a valid plugin". 
![image](https://user-images.githubusercontent.com/23131934/210324396-e8fc45ea-8c59-4deb-940a-8a8737152518.png)
And the files in the plugin folder are like this:
![image](https://user-images.githubusercontent.com/23131934/210324490-e902f77a-e0ef-4f57-ad60-a3804dd1ebad.png)
Do I need to add other related dll files into this folder to make the MESHIO.dll valid?
![image](https://user-images.githubusercontent.com/23131934/210324802-ffdaf98b-f48c-4ace-bdd8-2d8ef20f4314.png)

**Comment by asmaloney** [comment]
Oh! Yes you'll need those.

I didn't realize Windows was building assimp as a DLL. I'll take a look at the CMake to see why.

Edit: I'm clearly intending for it to be a static build:
```cmake
set( BUILD_SHARED_LIBS FALSE CACHE INTERNAL "override ASSIMP flags" FORCE )
```

**Comment by Niexiaoer** [comment]
Yes, I try to copy the three dll file into the same folder with the cloudcompare.exe and it works

**Comment by asmaloney** [comment]
Just to make sure we're working with the same code - you are using the MeshIO commit tagged "cloudcompare-2.11.x", right?

I'm not quite sure how to make this work properly. The assimp library is using a global CMake variable (`BUILD_SHARED_LIBS`) which I guess I can't turn off on Windows.

I'm also not seeing how you end up with a DLL for zlib or where pugixml is coming from.

Could you please try adding this to the MeshIO/CMakeLists.txt file?
```cmake
set( ASSIMP_BUILD_ZLIB TRUE CACHE INTERNAL "override ASSIMP flags" FORCE )
```

Then delete the previous DLL files and build it again?

**Comment by asmaloney** [comment]
I just noticed that the dates on your DLLs are not consistent and the file size of `MeshIO.dll` is different between the build directory and what you have installed.

Did you first try to build a recent version of CloudCompare/MeshIO and then back off to the 2.11.x version? pugixml is in a recent version of assimp, but not the older one.

Could you please remove the whole build directory and rebuild from scratch to see what you get?

**Comment by Niexiaoer** [comment]
> you are using the MeshIO commit tagged "cloudcompare-2.11.x", right?
>
Yes

> I just noticed that the dates on your DLLs are not consistent and the file size of `MeshIO.dll` is different between the build directory and what you have installed.
>
Actually, the difference between the size of MeshIO.dll is that one is from release mode and another is from releasewithdebuginfo, sorry for the confusion.
> 
> Did you first try to build a recent version of CloudCompare/MeshIO and then back off to the 2.11.x version? pugixml is in a recent version of assimp, but not the older one.

no


> I'm also not seeing how you end up with a DLL for zlib or where pugixml is coming from.
> 
For convenience, the assimp, zlib and pugixml are all build from vcpkg.

> set( ASSIMP_BUILD_ZLIB TRUE CACHE INTERNAL "override ASSIMP flags" FORCE )
>
I have tried this and rebuild the exe, still need to copy the three dll files

**Comment by asmaloney** [comment]
> For convenience, the assimp, zlib and pugixml are all build from vcpkg.

I don't understand. So you've modified MeshIO's CMake files to work with externally-built libraries?

**Comment by Niexiaoer** [comment]
yes, I make a little adjustment to the meshio cmake files to work with vcpkg. Maybe it is due to the adjustment? Just curious, under your assumption, is only one dll file(meshio.dll) generated in the build folder？

**Comment by asmaloney** [comment]
🤦  That's kind of critical information that would have saved me a couple of hours of digging through CMake files.

If you have modified it to use other libraries for some reason, then I have no idea what it's doing. It's designed to use only the parts it needs from a specific version of assimp which is compiled into the MeshIO plugin.

And yes it's supposed to be one DLL - I mentioned my surprise about assimp as a DLL [back here](https://github.com/asmaloney/MeshIO/issues/7#issuecomment-1369513956).
